module.exports = {
    APP_NAME: "",

    REPORT_LINK: "https://www.google.com.vn/",

    // FACEBOOK
    // Chatbot
    // FB_PAGE_ACCESS_TOKEN : 'EAAG7WfEhGK0BADqxAYZAAxnVMGZCE6qpLBqLZCsM9rCiqTxKnDQ9msX7ZCPEzUXHctcM1W5TcNHKZAqD6CrfkZBPwNA5ZCxj4wIDNuZAZC5TZCwP05Br1SzckdpMzCetUQppZAFOxzSEcintxwVMIgQ7ueSua4Fm81oNz0Tx1iRKqWrFbFGAiiZARZACENIx7QV0fALIZD',
    // Moi ngay
    FB_PAGE_ACCESS_TOKEN: "",
    FB_PAGE_VERIFY_TOKEN: "",
    FB_APP_SECRET: "",

    //HEROKU
    HEROKU_API_KEY: "",

    //OTHERS
    MAX_PEOPLE_WAITROOM: 10,
    MAX_WAIT_TIME_MINUTES: 30,

    //MONGODB
    PORT: 5000,
    MONGO_URI: "",
};
